/**
 * Copyright 2017 Solace Corp. http://solace.com
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
/**
 * GettingStartedSempConfig.java
 *
 * Alternated "Getting Started" example generated by swagger-codegen
 */

import com.solace.sempconfigclient.*;
import com.solace.sempconfigclient.auth.*;
import com.solace.sempconfigclient.model.*;
import com.solace.sempconfigclient.api.AclProfileApi;

import java.io.File;
import java.util.*;

class AclProfileApiExample {

    public static void main(String[] args) {
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        // change to your Solace Message Router URI
        defaultClient.setBasePath("http://AAA.BBB.CCC.DDD:8080/SEMP/v2/config");

        // Configure HTTP basic authorization: basicAuth
        HttpBasicAuth basicAuth = (HttpBasicAuth) defaultClient.getAuthentication("basicAuth");
        basicAuth.setUsername("username"); // change to your credentials
        basicAuth.setPassword("password"); // change to your credentials

        AclProfileApi apiInstance = new AclProfileApi();
        // change to your Message VPN name
        String msgVpnName = "default"; // String | The msgVpnName of the Message VPN.
        MsgVpnAclProfile body = new MsgVpnAclProfile(); // MsgVpnAclProfile | The ACL Profile object's attributes.

        // change to your ACL profile name
        body.setAclProfileName("acl-profile-from-semp-java");
        
        // List<String> select = Arrays.asList("select_example"); // List<String> | Include in the response only selected attributes of the object. See [Select](#select \"Description of the     syntax of the `select` parameter\").
        try {
            MsgVpnAclProfileResponse result = apiInstance.createMsgVpnAclProfile(msgVpnName, body, null);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling AclProfileApi#createMsgVpnAclProfile");
            e.printStackTrace();
        }
    }
}

